apiVersion: apps/v1
kind: Deployment
metadata:
  name: externalcheck
  labels:
    app: externalcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: externalcheck
  template:
    metadata:
      labels:
        app: externalcheck
    spec:
      containers:
        - name: externalcheck
          image: username/externalcheck:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5